### ISSUE TITLE
Pyramid Laplacian loss 

### ISSUE THREAD

**Issue by yucornetto** [MarcoForte/FBA_Matting#12]
Thanks for the great work! Your results are really impressive. I noticed that you suggested using laplacian loss for training. May I ask for the implementation details of it?

**Comment by MarcoForte** [comment]
Thanks! 
Here's the laplacian loss, 
https://gist.github.com/MarcoForte/a07c40a2b721739bb5c5987671aa5270
I based it off of this https://gist.github.com/alper111/b9c6d80e2dba1ee0bfac15eb7dad09c8
but I modified the code to support masking.

**Comment by yucornetto** [comment]
Thanks! That's very helpful

**Comment by MarcoForte** [comment]
I also want to add that the original code only worked for square images but my version works for rectangular ones also.

**Comment by bluesky314** [comment]
@MarcoForte What do you mean by 'masking' in your previous comment?

**Comment by kartikwar** [comment]
what is weight in the laplacian loss?

**Comment by kartikwar** [comment]
@yucornetto  and @bluesky314 were you able to figure out what is meant by masking or weight in the laplacian loss ?
