### ISSUE TITLE
About checkpoint!

### ISSUE THREAD

**Issue by CocoRLin** [MarcoForte/FBA_Matting#14]
Hi !
Your work show strong results on matting!
Could you please share us your best checkpoint with us for testing your network?

BTW,
Could you release the code of your losses?

**Comment by MarcoForte** [comment]
Hi here's the link for the checkpoint https://drive.google.com/file/d/1T_oiKDE_biWf2kqexMEN7ObWqtXAzbB1/view?usp=sharing

I'll be releasing full training code soon.
thanks for your interest!
