### ISSUE TITLE
Sensitivity to trimap

### ISSUE THREAD

**Issue by bluesky314** [MarcoForte/FBA_Matting#15]
Thanks for your great paper. I wanted to know how sensitive is your network to trimap input? I wanted to attach your network after my segmentation model which dilation/erosion to create trimap. Can you suggest how much I should dilate/erode and if this is a good method for your model.  Thanks!

Also will you be releasing training code any time soon?

**Comment by MarcoForte** [comment]
Hi yes what you suggest is possible with our model. I have not yet conducted the exact experiments on the sensitivity to trimap size, but I believe our model is far less sensitive than other matting models. This is due to the trimap-transformation that we do
