### ISSUE TITLE
script for foreground estimation

### ISSUE THREAD

**Issue by wchstrife** [MarcoForte/FBA_Matting#30]
I use [Code for foreground extension](https://github.com/MarcoForte/closed-form-matting/blob/master/solve_foreground_background.py) for foreground prediction on adobe dataset. But when processing some pictures, there will be insufficient memory.

I noticed that you mentioned that a custom multi-level solver written in C. Could you please provide this code？

**Comment by MarcoForte** [comment]
Hi I did not write the code for the multilevel solver so I can't provide you with it. But luckily someone else wrote a very similar solver and it is open source,  https://pymatting.github.io/pymatting.foreground.html#module-pymatting.foreground.estimate_foreground_ml

**Comment by wchstrife** [comment]
Thanks for your reply! this code solved my problem very well.

**Comment by 99991** [comment]
Sorry, I rewrote the documentation tool and the URL changed. This is the new URL for the foreground estimation function:

https://pymatting.github.io/foreground.html#estimate_foreground_ml
