### ISSUE TITLE
Foreground extension script doesn't work

### ISSUE THREAD

**Issue by PeterL1n** [MarcoForte/FBA_Matting#31]
I ran the foreground extension script you pointed to, but it does not seem to extend the foreground to the entire image. The surrounding areas are still black. Can you explain how you extend the foreground? Did you use some other method to extend the foreground to the entire image?

**Comment by MarcoForte** [comment]
One hack is to try set the pixels where alpha=0 to alpha=0.00001. I think
it should compute the foregrounds for all pixels then. Without affecting
the  result too much.
