### ISSUE TITLE
Loss function and  fba_fusion()

### ISSUE THREAD

**Issue by wchstrife** [MarcoForte/FBA_Matting#38]
in fba_decoder, there is a fba_fusion() function.
Is the loss function calculated by the output of the **fba_fusion()**? or the output of the **conv_up4()->clamp and sigmoid**

**Comment by MarcoForte** [comment]
Hi, the output of the *conv_up4()->clamp and sigmoid.*

**Comment by wchstrife** [comment]
Thank! So the fba_fusion() is only used during inference?

**Comment by MarcoForte** [comment]
Yes just inference should work well.
