### ISSUE TITLE
has the granting of your recent patent with Adobe effectively killed open source image matting?

### ISSUE THREAD

**Issue by 21pl** [MarcoForte/FBA_Matting#45]
https://patents.google.com/patent/US11004208B2/en

patent seems to cover the idea of user interaction to create binary matte -> trimap -> final matte and every variation of that.

**Comment by ilyaskhanbey** [comment]
interactive matting hmmm,  nany webservice are using interactive matting such  https://clippingmagic.com/

**Comment by MarcoForte** [comment]
Hi thank you for your interest in my work.
I am not a lawyer, and no longer an employee of Adobe so unfortunately I cannot give you a legal answer. 
Please contact representatives at Adobe for a more satisfying definitive answer.

**Comment by 21pl** [comment]
sorry - didn't mean to come off as so accusatory. Amazing work so far. Really looking forward to what you come up with next.
