### ISSUE TITLE
Real-world image inference

### ISSUE THREAD

**Issue by shkarupa-alex** [MarcoForte/FBA_Matting#5]
Is it possible to make inference on image without manual timap creation?

**Comment by MarcoForte** [comment]
Hi a trimap is neccesary for an accurate mask.

**Comment by 972461099** [comment]
hi,could you tell me how to get a trimap for a new image?sorry,i'm newbie

**Comment by MarcoForte** [comment]
No problem, I added a link to the readme with a video on how to create a trimap. The steps are listed in the video description also.
https://youtu.be/gl1XOAuMckM

**Comment by 972461099** [comment]
> No problem, I added a link to the readme with a video on how to create a trimap. The steps are listed in the video description also.
> https://youtu.be/gl1XOAuMckM

thanks, you are so patient
