### ISSUE TITLE
Matting on Mobile Devices

### ISSUE THREAD

**Issue by InternetMaster1** [MarcoForte/FBA_Matting#8]
Thanks, and congratulations on SOTA! Wow... You guys are on top of the alphamatting charts.

Sorry for the newbie questions

1. Can this algorithm be used on mobile devices for image matting? Or you feel this is too heavy for the task? Can you point me in the right direction?

2. Can automated trimap generation libraries be used? Or the quality of the trimap matters too in getting good results? I am wondering how to do automation without any manual intervention.
e.g. https://github.com/lnugraha/trimap_generator
or 
opencv erode and dilate methods

**Comment by MarcoForte** [comment]
Thanks for your interest! 
1. This network architecture may be a bit heavy for mobile. For example, Group Normalization is not as computationally efficient as batch-norm at test-time. Some of my findings can be applied to this work https://arxiv.org/abs/1905.06747
2. They can be used certainly. Trimap doesn't have to be extremely tight.
