### ISSUE TITLE
interactiveMatting by click

### ISSUE THREAD

**Issue by zongking123** [MarcoForte/FBA_Matting#9]
Do you think it's possible to achieve Matting by clicking on an interactive method, such as 99% accurate interactive object selection with just a few clicks and fba-matting, in your paper?

**Comment by 983** [comment]
There is no method that can achieve 99% accuracy even with perfect trimaps. The problem is just too hard for that.

**Comment by MarcoForte** [comment]
I agree with @983  it is  very difficult in the general case. However for simple objects where the transparency is contained in a narrow boundary around the object then a trimap could be generated by dilating the predicted mask
